### ISSUE TITLE
[프로젝트 할일 및 일정 관리]

### ISSUE THREAD

**Issue by jectgenius** [jectgenius/java-with-increpas#1]
# 🌈 Success criteria
1. 

# 👷To-do
- [x] 깃허브 프로젝트 생성
- [x] 깃허브 마일스톤 생성
- [x] 깃허브 이슈 작성 및 담당자 할당
- [x] 깃허브 이슈들을 마일스톤 단위로 묶기

# 👓 Review
1.
